kind: pipeline
name: default

steps:
- name: Build
  image: python
  commands:
  - pip install -r requirements.txt

- name: Publish
  image: plugins/docker
  settings:
    username:
      from_secret: u_docker
    password: 
      from_secret: p_docker
    repo: mansong/drone-harness-plugin
    auto_tag: true

- name: Harness-Deploy
  image: luisredda/drone-harness-plugin-param
  settings:  
    application: "Harness Demo Application"
    type: "PIPELINE"
    entityname: "CD Pipeline"
    service: "search"
    build: "v6"
    accountid:
      from_secret: harness_acctid
    apikey: 
      from_secret: harness_secret
    service_name: "order-service"
    build_number: "latest"
    artifact_source_name: "harness_todolist-sample"