kind: pipeline
name: ci

steps:

- name: build
  image: python
  commands:
  - pip install -r requirements.txt 

- name: dockerlint
  image: hadolint/hadolint:latest-alpine
  commands:
  - hadolint Dockerfile

- name: imagescan
  image: aquasec/trivy
  commands:
  - trivy fs --security-checks vuln,config ./

- name: publish
  image: plugins/docker
  settings:
    username:
      from_secret: u_docker
    password: 
      from_secret: p_docker
    repo: mansong/drone-harness-plugin
    auto_tag: true
  depends_on:
    - imagescan

- name: harness deploy
  image: rlachhman/drone-harness-trigger:1.0.0
  settings:
    accountid:
      from_secret: harness_acctid
    apikey: 
      from_secret: harness_secret
    harnessservicename: "order-service"
    artifactversion: "131"
    harnessartifactname: "harness_todolist-sample"
    harnesswebhookid: "PR0pVTtHsHhq28EYXACrzZIXGdL75OnRyJm3jhQ5"
  depends_on:
    - publish

---
kind: pipeline
type: docker
name: audit

steps:

- name: audit
  image: pyupio/safety
  commands:
    - safety check