kind: pipeline
name: ci

steps:

- name: build
  image: python
  commands:
  - pip install -r requirements.txt 

- name: dockerlint
  image: hadolint/hadolint:latest-alpine
  commands:
  - hadolint Dockerfile

- name: imagescan
  image: aquasec/trivy
  commands:
  - trivy fs --security-checks vuln,config ./

- name: publish
  image: plugins/docker
  settings:
    username:
      from_secret: u_docker
    password: 
      from_secret: p_docker
    repo: mansong/drone-harness-plugin
    auto_tag: true
  depends_on:
    - imagescan

- name: harness deploy
  image: luisredda/drone-harness-plugin-param
  settings:  
    application: "Harness Demo Application"
    type: "PIPELINE"
    entityname: "CD Pipeline"
    service: "search"
    build: "v6"
    accountid:
      from_secret: harness_acctid
    apikey: 
      from_secret: harness_secret
    service_name: "order-service"
    build_number: "latest"
    artifact_source_name: "harness_todolist-sample"

---
kind: pipeline
type: docker
name: audit

steps:

- name: audit
  image: pyupio/safety
  commands:
    - safety check